AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  helloworldpython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: A starter AWS Lambda function.
      Runtime: python2.7
      Handler: lambda_function.lambda_handler
      CodeUri: ./src
      Policies:
        - "AWSConfigRulesExecutionRole"
        - "AWSLambdaDynamoDBExecutionRole"
      MemorySize: 128
      Timeout: 3
  MyTable:
     Type: AWS::Serverless::SimpleTable
